# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-19 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(default=None, max_length=100, verbose_name='Тех информация')),
                ('about', models.CharField(default=None, max_length=10000, verbose_name='Информация о боте')),
                ('functions', models.CharField(default=None, max_length=10000, verbose_name='Возможности бота')),
                ('contacts', models.CharField(default=None, max_length=10000, verbose_name='Контакты, инфа о сотрудничестве')),
            ],
            options={
                'verbose_name': 'Инфо',
                'verbose_name_plural': 'Инфо',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None, verbose_name='Id телеграм пользователя')),
                ('first_name', models.CharField(default=None, max_length=100, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(default=None, max_length=100, verbose_name='Фамилия пользователя')),
                ('username', models.CharField(default=None, max_length=100, verbose_name='Никнэйм пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
