# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-10 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('event_date', models.DateField(verbose_name='Дата мероприятия')),
                ('event_time', models.TimeField(verbose_name='Время начала мероприятия')),
                ('event_place', models.CharField(max_length=255, verbose_name='Название площадки')),
                ('event_event_url', models.URLField(verbose_name='Ссылка на встречу вконтакте')),
                ('event_image', models.ImageField(upload_to='', verbose_name='Афиша мероприятия')),
                ('event_contacts', models.CharField(max_length=255, verbose_name='Контакты оргов')),
            ],
            options={
                'verbose_name': 'Мероприятия и туры',
            },
        ),
        migrations.CreateModel(
            name='VkGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_city', models.CharField(max_length=255, verbose_name='Город')),
                ('group_name', models.CharField(max_length=255, verbose_name='Название бара или клуба')),
                ('group_url', models.URLField(max_length=255, verbose_name='Ссылка на группу в Vk')),
                ('group_domain', models.CharField(max_length=255, verbose_name='Домен или id группы')),
                ('group_tag', models.CharField(max_length=15, verbose_name='Тэг группы, нужен для парсера')),
            ],
            options={
                'verbose_name': 'Группы',
            },
        ),
    ]
