# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-11 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_data_grub', '0002_auto_20200110_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_event_url',
            new_name='event_url',
        ),
        migrations.AddField(
            model_name='vkgroups',
            name='group_afisha_id',
            field=models.CharField(default='None', max_length=15, verbose_name='Id афиши'),
        ),
        migrations.AddField(
            model_name='vkgroups',
            name='group_id',
            field=models.CharField(default='None', max_length=15, verbose_name='Id группы, в начале строки обязателен знак -'),
        ),
    ]
