# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-16 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_data_grub', '0005_auto_20200115_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_time',
        ),
        migrations.AddField(
            model_name='events',
            name='event_datetime',
            field=models.DateTimeField(default=None, verbose_name='Дата и время'),
        ),
    ]
