# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-16 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_data_grub', '0006_auto_20200116_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_domain',
            field=models.CharField(default=None, max_length=255, verbose_name='домен мероприятия'),
        ),
    ]
