# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-19 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_data_grub', '0008_botinfo_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.IntegerField(default=None, verbose_name='Id телеграм пользователя'),
        ),
    ]
